### ISSUE TITLE
Hilangnya nomor 28 dan terpotongnya nomor 29

### ISSUE THREAD

**Issue by RimuEirnarn** [UnknownRori/smk1kltu-repo#1]
Sebuah misteri baru telah bermunculan. Diduga konten pertemuan nomor 28 dan 29 berada dalam atap yang sama namun nomor 28 hilang dan nomor 29 dimakan sebagian.

Apakah badan kepolisian dapat menyelesaikan kasus pembunuhan ini?

**Comment by UnknownRori** [comment]
tipo level tinggi

**Comment by RimuEirnarn** [comment]
pengen pake emot maoi tapi kagak ada
