### ISSUE TITLE
[Error 404] Folder Video tidak ditemukan

### ISSUE THREAD

**Issue by RimuEirnarn** [UnknownRori/smk1kltu-repo#11]
seperti judulnya, file terefek: https://github.com/UnknownRori/smk1kltu-repo/blob/main/lecture/video/README.md

![image](https://user-images.githubusercontent.com/75618825/233209252-1251c734-6550-4e8e-a33b-58fa5fda51f9.png)

**Comment by UnknownRori** [comment]
my god, tinggal di re open issue lama

**Comment by UnknownRori** [comment]
Coba ini https://drive.google.com/drive/folders/14MESiCgHaIPzUP3xJH3tJy1ywjHmQtQl?usp=sharing
