### ISSUE TITLE
Contoh kosong dan judulnya salah

### ISSUE THREAD

**Issue by RimuEirnarn** [UnknownRori/smk1kltu-repo#3]
Di file pertemuan 28, tepatnya [ini](https://github.com/UnknownRori/smk1kltu-repo/blob/main/lecture/md/Pertemuan%2028%20-%20Recap%20Materi%20PHP%20Mysql/pertemuan-28-recap-materi-php-mysql.md) ada contoh kosong.

Sepertinya memang dilupakan dan akan berakhir dilupakan? tak ada yang tau.

**Comment by RimuEirnarn** [comment]
Hmm, yes 28 menjadi 29 lagi

**Comment by UnknownRori** [comment]
oh no, mungkin aku push sekarang baru bener
