### ISSUE TITLE
File besar menganggu proses kloning

### ISSUE THREAD

**Issue by RimuEirnarn** [UnknownRori/smk1kltu-repo#9]
Tipikalnya, file `.mp4` akan menganggu proses kloning repo karena ukurannya yang besar. Saran penyelesaian sebagai berikut:

- Upload ke Google Drive lalu buat file `.txt` atau `.md` sebagai pengganti. Hal ini membuat ukuran repo tidak terlalu besar ketika sudah mulai banyak. (Maksimal 1GB)

> Untuk upload ke Google Drive, kusarankan menggunakan shared folder agar memudahkan banyak hal kedepannya.

**Comment by UnknownRori** [comment]
mungkin nanti aku mulai upload ke google drive, mungkin, tapi bisa saja aku lupa

**Comment by RimuEirnarn** [comment]
kalau kelupaan bisa jadi masalah

**Comment by UnknownRori** [comment]
Done, udah aku hapus di folder `lecture/video` plus aku rebase squash e19ac61a950d830df4bd34298c0dcf32e110865e

https://drive.google.com/drive/folders/14MESiCgHaIzUP3xJH3tJy1ywjHmQtQl?usp=sharing

**Comment by RimuEirnarn** [comment]
PDF keknya juga perlu dipindah ke GoogleDrive, masalahnya seharusnya lebih enak clone cuma buat ngurusin blob .md daripada ngurusin literal blob PDF

**Comment by RimuEirnarn** [comment]
keknya gampang kalau ngomong: blob apapun kecuali blob buat tugas dimasukin ke gdrive

**Comment by RimuEirnarn** [comment]
![image](https://user-images.githubusercontent.com/75618825/234311296-9ea58097-84d1-46a5-9f80-decd38b66864.png)

menunggu repo owner buat ngurusin masalah ini

![image](https://user-images.githubusercontent.com/75618825/234311599-edab928d-f4b9-4556-8775-b87f9e963b7b.png)

ukuran folder pdf-nya

**Comment by RimuEirnarn** [comment]
btw, log cloneku:

![image](https://user-images.githubusercontent.com/75618825/234312703-7bb6937f-d4a6-4f92-8325-2aa5c155d789.png)

butuh waktu yang lama gegara perangkatku selalu dibawah 50KiB/s (0.4Mb/s Task Manager) buat download

**Comment by UnknownRori** [comment]
astaga

**Comment by RimuEirnarn** [comment]
kayaknya gak mau di fix

**Comment by UnknownRori** [comment]
udah aku upload di google drive yang tadi, kalau urusan file pdf di hapus kapan kapan, sekalian nanti di squash merge, kalau pengen, antum aja bikin pr, aku paling besok

**Comment by UnknownRori** [comment]
udah aku upload di google drive yang tadi, kalau urusan file pdf di hapus kapan kapan, sekalian nanti di squash merge, kalau pengen, antum aja bikin pr, aku paling besok

**Comment by UnknownRori** [comment]
dah aku force push
